#FROM php:7.3.11-apache

FROM thecodingmachine/php:7.3-v3-apache

#RUN apt-get update &&\
#    apt-get install --no-install-recommends --assume-yes --quiet ca-certificates curl git &&\
#    rm -rf /var/lib/apt/lists/*

#RUN pecl install xdebug-2.7.0 && docker-php-ext-enable xdebug
#RUN echo 'zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)' >> /usr/local/etc/php/php.ini
##RUN echo 'zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so"' >> /usr/local/etc/php/php.ini
#RUN echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/php.ini
#RUN echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/php.ini
#RUN echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/php.ini