#!/bin/bash

# a library of shared variables/constants

# Set-up some colours
BLUE='\033[34m'
RED='\033[31m'
YELLOW='\033[33m'
WHITE='\033[37m'
GREEN='\033[32m'
RESET='\033[0m'
BOLD='\033[1m'
BLINK='\033[5m'
INVERSE='\033[7m'
UNDERLINE='\033[4m'

# Set database variables
DB_PORT="5432"
DB_HOST="localhost"
DB_INSTALL="darin"

# docker
DOCKER_YAML="../docker/docker-compose.yml"